<<<<<<< HEAD
# Basic
title: jinx
subtitle: ä¸ªäººç«™
description: æ¬¢è¿Žæ¥åˆ°æˆ‘çš„ä¸ªäººç«™~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: jinx
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: EDG
url: "http://wanzijinx.github.io"

# Comment
comments:
    disqus: jinxx

# Social
social:
    weibo: 2442630841 
    github: wanzijinx
    # twitter: 
    mail: 15751865396@163.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·åŽ»æŽ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id:   

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·åŽ»æŽ‰æˆ–è€…æ›´æ¢ id
ga:
    id:   
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ðŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºŽæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"



theme: jekyll-theme-cayman
=======
# Welcome to Jekyll!
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
excerpt_separator: ""
title: Aquarius
email: 939811456@qq.com
description: > # this means to ignore newlines until "baseurl:"
  ä½ å¥½ï¼Œæ¬¢è¿Žæ¥åˆ°æˆ‘çš„åšå®¢ï¼å¸Œæœ›æˆ‘çš„åšæ–‡èƒ½å¯¹ä½ æœ‰æ‰€å¸®åŠ©ã€‚â€”â€”Aquarius
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
>>>>>>> fc3cf4440b333ece76c1e914d14ad95649484eab
